CREATE TABLE IF NOT EXISTS `users`(
	`id` int NOT NULL AUTO_INCREMENT,
	`tempreg` varchar(150) CHARACTER SET utf8 NOT NULL,
	`status` enum('Hot', 'Warm', 'Cold') DEFAULT 'Warm',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
